workers_dev = true
name = "sprose"
compatibility_date = "2025-02-09"
main = "./worker.ts"

[assets]
directory = "./build/client/"
binding = "ASSETS"
run_worker_first = false

[observability.logs]
enabled = true
