# workers_dev = true
name = "sprose"
compatibility_date = "2025-02-09"
# main = "./worker.ts"
pages_build_output_dir = "./build/client"

# [assets]
# directory = "./build/client/"
# binding = "ASSETS"
# run_worker_first = false

# [observability.logs]
# enabled = true
